#!/usr/bin/env node
// Generates src/styles/tokens.css (a Tailwind v4 @theme block) from design/DESIGN.md (YAML frontmatter)
// and the "## Tokens" section of design/SHELL.md. Colours are never hand-copied into the web app:
// change the design files and re-run `npm run tokens`. `--check` fails if the committed file is stale.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parse } from "yaml";

const HERE = dirname(fileURLToPath(import.meta.url));
const DESIGN_DIR = join(HERE, "..", "..", "..", "design");
const OUT = join(HERE, "..", "src", "styles", "tokens.css");

export function designFrontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error("DESIGN.md has no YAML frontmatter");
  return parse(m[1]);
}

// "- bg surface #f8f9ff · container-low #eff4ff · border #bfc7d2 (use #dbe3ee for hairlines inside cards)"
export function shellColors(md) {
  const section = tokensSection(md);
  const out = {};
  for (const line of section.split(/\r?\n/)) {
    if (!line.startsWith("- ")) continue;
    for (const raw of line.slice(2).split("·")) {
      const hairline = raw.match(/use (#[0-9a-f]{6}) for hairlines/i);
      if (hairline) out.hairline = hairline[1].toLowerCase();
      const item = raw.replace(/\([^)]*\)/g, " ").trim();
      const m = item.match(/^(?:bg\s+)?([a-z][a-z-]*)\s+(#[0-9a-f]{6})$/i);
      if (m) out[m[1].toLowerCase()] = m[2].toLowerCase();
    }
  }
  return out;
}

// "- Type ramp: page title 24/600 (-0.02em) · section 15/600 · body 14/400 lh 20 · small 12/400 lh 16 · label 11/600 ..."
export function shellType(md) {
  const line = tokensSection(md).split(/\r?\n/).find((l) => l.includes("Type ramp:"));
  if (!line) throw new Error("SHELL.md has no 'Type ramp' line");
  const out = {};
  for (const raw of line.split(":").slice(1).join(":").split("·")) {
    const m = raw.trim().match(/^([a-z ]+?)\s+(\d+)\/(\d+)(?:\s*\((-?[\d.]+em)\))?(?:.*?\blh\s+(\d+))?(?:.*?tracking\s+(-?[\d.]+em))?/i);
    if (!m) continue;
    const name = m[1].trim().split(" ").pop(); // "page title" -> "title"
    out[name] = { size: `${m[2]}px`, weight: m[3], tracking: m[4] || m[6] || null, lineHeight: m[5] ? `${m[5]}px` : null };
  }
  return out;
}

// "- Radius: cards 10px, controls 8px, chips 999px. ... Control height 36px. Sidebar item 34px."
export function shellMetrics(md) {
  const px = (re, text = tokensSection(md)) => {
    const m = text.match(re);
    if (!m) throw new Error(`SHELL.md: cannot find ${re}`);
    return `${m[1]}px`;
  };
  return {
    radius: { card: px(/cards (\d+)px/), control: px(/controls (\d+)px/), chip: px(/chips (\d+)px/) },
    // the sidebar width lives in the "## Frame" section: "sidebar 232px + main flex 1"
    spacing: { control: px(/Control height (\d+)px/), nav: px(/Sidebar item (\d+)px/), sidebar: px(/sidebar (\d+)px/, md) },
  };
}

function tokensSection(md) {
  const section = md.split(/^## /m).find((s) => s.startsWith("Tokens"));
  if (!section) throw new Error("SHELL.md has no '## Tokens' section");
  return section;
}

export function render(designMd, shellMd) {
  const design = designFrontmatter(designMd);
  const colors = { ...design.colors, ...shellColors(shellMd) }; // SHELL.md is what the screens use; it wins
  const type = shellType(shellMd);
  const metrics = shellMetrics(shellMd);
  const fam = (t) => design.typography[t].fontFamily;
  const lines = [
    "/* Generated by apps/web/scripts/tokens.mjs from design/DESIGN.md and design/SHELL.md. Do not edit. */",
    "@theme {",
    ...Object.entries(colors).map(([k, v]) => `  --color-${k}: ${String(v).toLowerCase()};`),
    `  --font-sans: "${fam("body-md")}", system-ui, sans-serif;`,
    `  --font-mono: "${fam("code-md")}", ui-monospace, monospace;`,
    ...Object.entries(type).flatMap(([k, t]) => [
      `  --text-${k}: ${t.size};`,
      `  --text-${k}--font-weight: ${t.weight};`,
      ...(t.lineHeight ? [`  --text-${k}--line-height: ${t.lineHeight};`] : []),
      ...(t.tracking ? [`  --text-${k}--letter-spacing: ${t.tracking};`] : []),
    ]),
    ...Object.entries(metrics.radius).map(([k, v]) => `  --radius-${k}: ${v};`),
    ...Object.entries(metrics.spacing).map(([k, v]) => `  --spacing-${k}: ${v};`),
    "}",
    "",
  ];
  return lines.join("\n");
}

function main() {
  const css = render(readFileSync(join(DESIGN_DIR, "DESIGN.md"), "utf8"), readFileSync(join(DESIGN_DIR, "SHELL.md"), "utf8"));
  if (process.argv.includes("--check")) {
    const current = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== css) {
      console.error("src/styles/tokens.css is stale: run `npm run tokens` and commit the result.");
      process.exit(1);
    }
    console.log("tokens.css is up to date");
    return;
  }
  writeFileSync(OUT, css);
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
